using System;
using System.IO;
using System.Windows.Forms;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace BreakReminderInstaller
{
    class Program
    {
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            
            DialogResult dr = MessageBox.Show(
                "Do you want to install Break Reminder on this computer?\n\nIt will be installed to your local profile and added to the Start Menu.",
                "Break Reminder Setup", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (dr != DialogResult.Yes) return;
            
            try
            {
                string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                string installDir = Path.Combine(localAppData, "BreakReminder");
                
                if (!Directory.Exists(installDir))
                {
                    Directory.CreateDirectory(installDir);
                }
                
                string exePath = Path.Combine(installDir, "BreakReminder.exe");
                
                string b64 = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAFS7nWoAAAAAAAAAAOAAAgELAQsAABoAAAAIAAAAAAAA7jkAAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAIAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAJw5AABPAAAAAEAAAPAEAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAA9BkAAAAgAAAAGgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAPAEAAAAQAAAAAYAAAAcAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAIgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADQOQAAAAAAAEgAAAACAAUApCcAAPgRAAABAAAAAgAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMwAwDcAAAAAQAAEQAoBQAACgAWKAYAAAoAKAcAAAYAcwcAAAqABQAABH4FAAAEFP4GAwAABnMIAAAKbwkAAAoAcwoAAAqABAAABH4EAAAEcgEAAHBvCwAACgB+BAAABCgMAAAGbwwAAAoAKAQAAAYAfgQAAAR+BQAABG8NAAAKAH4EAAAEF28OAAAKAHMPAAAKgAYAAAR+BgAABCDoAwAAbxAAAAoAfgYAAAQU/gYFAAAGcwgAAApvEQAACgAoEgAACgoSAH4HAAAEbCgTAAAKgAgAAAR+BgAABG8UAAAKACgVAAAKACoiACgEAAAGACoAAAATMAMAJAEAAAIAABEAfgUAAARvFgAACm8XAAAKAH4IAAAEKBIAAAooGAAACgoSACgZAAAKIwAAAAAAAAAA/gQW/gETBhEGLQZ+GgAACgpyHwAAcBIAKBsAAAqMEQAAARIAKBwAAAqMEQAAASgdAAAKCwdzHgAACgwIFm8fAAAKAHJRAABwFP4GBgAABnMIAAAKcyAAAAoNcmMAAHAU/gYKAAAGcwgAAApzIAAAChMEEQQoCQAABm8hAAAKAHKTAABwFP4GCwAABnMIAAAKcyAAAAoTBX4FAAAEbxYAAAoIbyIAAAomfgUAAARvFgAACnKdAABwbyMAAAomfgUAAARvFgAACglvIgAACiZ+BQAABG8WAAAKEQRvIgAACiZ+BQAABG8WAAAKEQVvIgAACiYqEzAGAOgAAAADAAARAH4IAAAEKBIAAAooGAAACgoSACgZAAAKIwAAAAAAAAAA/gMMCC18AH4GAAAEbyQAAAoAcqEAAHB+JQAACiAJAAEAKAEAAAYmcrcAAHB+BwAABIwRAAABKCYAAApyaAEAcBYfQBYgAAACACgnAAAKJhR+JQAAChYoAQAABiYoEgAACg0SA34HAAAEbCgTAAAKgAgAAAR+BgAABG8UAAAKAAArRAByHwAAcBIAKBsAAAqMEQAAARIAKBwAAAqMEQAAASgdAAAKC34EAAAEBxYfPwdvKAAACigpAAAKbyoAAApvCwAACgAAKhMwBAC+AQAABAAAEQBzKwAAChMEEQQgLAEAAG8sAAAKABEEIJYAAABvLQAACgARBBlvLgAACgARBHJRAABwby8AAAoAEQQXbzAAAAoAEQQWbzEAAAoAEQQWbzIAAAoAEQQKczMAAAoTBREFHxRvNAAACgARBR8UbzUAAAoAEQVyjAEAcG8vAAAKABEFIPoAAABvLAAACgARBQtzNgAAChMGEQYfFG80AAAKABEGHzJvNQAACgARBh9kbywAAAoAEQYXczcAAApvOAAACgARBiCgBQAAczcAAApvOQAACgARBn4HAAAEKDoAAApvOwAACgARBgxzPAAAChMHEQdyzAEAcG8vAAAKABEHIJYAAABvNAAACgARBx9kbywAAAoAEQcfMm81AAAKABEHF289AAAKABEHDQZvPgAACgdvPwAACgAGbz4AAAoIbz8AAAoABm8+AAAKCW8/AAAKAAYJb0AAAAoABm9BAAAKF/4BFv4BEwgRCC1TAAhvQgAACihDAAAKgAcAAAQoCAAABgAoEgAAChMJEgl+BwAABGwoEwAACoAIAAAEctIBAHB+BwAABIwRAAABKCYAAApyHgIAcBYfQChEAAAKJgAqAAAbMAIARgAAAAUAABEAAH4JAAAEKEUAAAoW/gEMCC0pAH4JAAAEKEYAAAoKBm9HAAAKEgEoSAAAChb+AQwILQgAB4AHAAAEAAAA3gUmAADeAAAqAAABEAAAAAABAD4/AAUBAAABCzACACEAAAAAAAAAAAB+CQAABH8HAAAEKEkAAAooSgAACgAA3gUmAADeAAAqAAAAARAAAAAAAQAZGgAFAQAAARswAwBqAAAABgAAEQAAfksAAApyPAIAcBZvTAAACgoABhT+AQ0JLSoABnKYAgBwb00AAAoLBxT+AQ0JLRQAB29OAAAKKE8AAAooUAAACgzeIgAA3hAGFP4BDQktBwZvUQAACgDcAADeBSYAAN4AABYMKwAACCoAAAEcAAACABMANkkAEAAAAAAAAAEAXF0ABQEAAAEbMAMAYgAAAAcAABEAAH5LAAAKcjwCAHAXb0wAAAoKACgJAAAGFv4BCwctEQAGcpgCAHAWb1IAAAoAACsTAAZymAIAcChPAAAKb1MAAAoAAADeEAYU/gELBy0HBm9RAAAKANwAAN4FJgAA3gAAKgAAARwAAAIAEwA0RwAQAAAAAAAAAQBaWwAFAQAAAVIAfgQAAAQWbw4AAAoAKFQAAAoAKgAAABswBgBkAAAACAAAEQAfQB9Ac1UAAAoKBihWAAAKCwAHH0wgrwAAAB9QKFcAAApvWAAACgAHKFkAAAofEB8QHyAfIG9aAAAKAADeEgcU/gETBBEELQcHb1EAAAoA3AAGb1sAAAoMCChcAAAKDSsACSoBEAAAAgASAC0/ABIAAAAASh8UgAcAAARytAIAcIAJAAAEKgBCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMxOQAAAAAFAGwAAACEBQAAI34AAPAFAADwBgAAI1N0cmluZ3MAAAAA4AwAAMwCAAAjVVMArA8AABAAAAAjR1VJRAAAALwPAAA8AgAAI0Jsb2IAAAAAAAAAAgAAAVcdAhQJAAAAAPolMwAWAAABAAAALwAAAAIAAAAJAAAADQAAAA0AAABcAAAAAwAAAAMAAAAIAAAAAQAAAAEAAAABAAAAAwAAAAAACgABAAAAAAAGAEIAOwAKAIUAcAAKAJkAcAAKAK4AcAAGAMoAOwAGAO0AOwAOAHIBYwEGAMIBogEGAOgBogEGACUCBgIGAEICOwAKAFUCcAAGAJYCOwAKAA4DcAA7ABMDAAAGADoDOwAGAHQDOwAGAIYDOwAKAJQDcAAGAL4DOwAKAMUDcAAKANADcAAKAN0DcAAKAO8DcAAKAP4DcAAKABYEcAAGADgEOwAKAEsEcAAKAFAEcAAKAG0EcAAKAJEEcAAKANUEcAAKAOwEcAAGAPoEOwAKADAFcAB3AEgFAAAKAGcFcAAGALIFqAUGAP4F7gUGAAcG7gUGAFIGOwAOAIAGYwEOAIcGYwEOAJAGYwEOAKAGYwEOAK8GYwEOALcGYwEAAAAAAQAAAAAAAQABAIABEAAcACQABQABAAEAUYBJAAoAUYBTAAoAUYBdAAoAEQCQACMAEQClACcAEQC0ACsAEQC6AC8AEQDTADIAEQDdADYAAAAAAIAAkSBmABwAAQBQIAAAAACRAOgAOQAEADghAAAAAJEA9wA9AAQARCEAAAAAkQAGATkABgB0IgAAAACRABEBPQAGAGgjAAAAAJEAHAE9AAgANCUAAAAAkQAnATkACgCYJQAAAACRADIBOQAKANglAAAAAJEAPQFEAAoAbCYAAAAAkQBQAT0ACgD4JgAAAACRAFwBPQAMABAnAAAAAJEAdwFRAA4AkCcAAAAAkRjnBjkADgAAAAEAggEAAAIAiwEAAAMAkAEAAAEAmQEAAAIAoAEAAAEAmQEAAAIAoAEAAAEAmQEAAAIAoAEAAAEAmQEAAAIAoAEAAAEAmQEAAAIAoAFBAOIBVgBJAOIBWwBRAOIBXwBZAOIBWwBhAGECOQBhAHQCZAAZAOIBWwBpAOIBaQAZAKMCbwARAOIBWwARAK0CXwARALYCdQARAL8CewARAM8CgQAhAOIBWwAhANsCVgAhAOgCbwApAPEChgApAPkCiwAhAAQDWwBhAAoDOQBxACYDlgB5ADQDWwApAEMDmwCBAFIDpACBAGMDqACBAGgDrACBAHoDrACRAI0DsACZAOIBXwCZAJ0DgQCZAOIBtwCZAKkDgQB5ALUDvgB5ALUDxAAhALkDWwChAGMD2QCRAI0D3ACpACgE4gCRAC0ErADZAD0E8QCRAEEE9wDhAOIBWwDpAFgEVgDpAGIEVgDhAH0EBgHpAK0CXwDhAKMEDAHhALUEgQDhAMUEgQABAeIBWwDpANsEVgDpAOQEVgAJAeIBWwARAeIBVgAJAQIFEgEJAQ4FEgERARoFGQEJASYFEgEZAeIBWwAZATcFIAHpAFoFJgEhAbUDLAHhAHYFMgHhAIcFOQEJAZIFPgERAZwFRAGpACgESwExAbcFcgExAb4FdwGRAMoFfAGJAM8FgAGJANgFfAExAeEFjQE5ARMGkwFBAR8GmAFBASoGoAEJANgFfAFhADMGpQGRAEYGqQFJAV4GWwBBAWYGuAFBAXIGvgFhAHsGOQBRAeIBywFZAZYG0QFpAaYG2gFZATQD4wFxAb0G6gFZAccG8AFRAdMG+wE5ANwG/wEJAAQADQAJAAgAEgAJAAwAFwAuAAsAEgIuABMAGwJAACMAEgCRAMoA/QBWAYcBrwHEAQUCOAJAAQMAZgABAASAAAAAAAAAAAAAAAAAAAAAACQAAAAEAAAAAAAAAAAAAAABADIAAAAAAAQAAAAAAAAAAAAAAAEAcAAAAAAABAAAAAAAAAAAAAAASABjAQAAAAAAAAA8TW9kdWxlPgBCcmVha1JlbWluZGVyLmV4ZQBQcm9ncmFtAEJyZWFrUmVtaW5kZXIAbXNjb3JsaWIAU3lzdGVtAE9iamVjdABTTkRfQUxJQVMAU05EX0FTWU5DAFNORF9MT09QAFBsYXlTb3VuZABTeXN0ZW0uV2luZG93cy5Gb3JtcwBOb3RpZnlJY29uAHRyYXlJY29uAENvbnRleHRNZW51AHRyYXlNZW51AFRpbWVyAHRpbWVyAGludGVydmFsTWludXRlcwBEYXRlVGltZQBuZXh0QnJlYWsAY29uZmlnUGF0aABNYWluAEV2ZW50QXJncwBUcmF5TWVudV9Qb3B1cABVcGRhdGVNZW51AFRpbWVyX1RpY2sAT25TZXR0aW5ncwBMb2FkQ29uZmlnAFNhdmVDb25maWcASXNBdXRvU3RhcnRFbmFibGVkAE9uQXV0b1N0YXJ0AE9uRXhpdABTeXN0ZW0uRHJhd2luZwBJY29uAENyZWF0ZUljb24AcHN6U291bmQAaG1vZABmZHdTb3VuZABzZW5kZXIAZQBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUALmN0b3IAUnVudGltZUNvbXBhdGliaWxpdHlBdHRyaWJ1dGUAU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzAERsbEltcG9ydEF0dHJpYnV0ZQB3aW5tbS5kbGwAU1RBVGhyZWFkQXR0cmlidXRlAEFwcGxpY2F0aW9uAEVuYWJsZVZpc3VhbFN0eWxlcwBTZXRDb21wYXRpYmxlVGV4dFJlbmRlcmluZ0RlZmF1bHQARXZlbnRIYW5kbGVyAGFkZF9Qb3B1cABzZXRfVGV4dABzZXRfSWNvbgBzZXRfQ29udGV4dE1lbnUAc2V0X1Zpc2libGUAc2V0X0ludGVydmFsAGFkZF9UaWNrAGdldF9Ob3cAQWRkTWludXRlcwBTdGFydABSdW4ATWVudQBNZW51SXRlbUNvbGxlY3Rpb24AZ2V0X01lbnVJdGVtcwBDbGVhcgBUaW1lU3BhbgBvcF9TdWJ0cmFjdGlvbgBnZXRfVG90YWxTZWNvbmRzAFplcm8AZ2V0X01pbnV0ZXMASW50MzIAZ2V0X1NlY29uZHMAU3RyaW5nAEZvcm1hdABNZW51SXRlbQBzZXRfRW5hYmxlZABzZXRfQ2hlY2tlZABBZGQAU3RvcABJbnRQdHIATWVzc2FnZUJveABEaWFsb2dSZXN1bHQATWVzc2FnZUJveEJ1dHRvbnMATWVzc2FnZUJveEljb24ATWVzc2FnZUJveERlZmF1bHRCdXR0b24ATWVzc2FnZUJveE9wdGlvbnMAU2hvdwBnZXRfTGVuZ3RoAE1hdGgATWluAFN1YnN0cmluZwBGb3JtAENvbnRyb2wAc2V0X1dpZHRoAHNldF9IZWlnaHQARm9ybUJvcmRlclN0eWxlAHNldF9Gb3JtQm9yZGVyU3R5bGUARm9ybVN0YXJ0UG9zaXRpb24Ac2V0X1N0YXJ0UG9zaXRpb24Ac2V0X01heGltaXplQm94AHNldF9NaW5pbWl6ZUJveABMYWJlbABzZXRfTGVmdABzZXRfVG9wAE51bWVyaWNVcERvd24ARGVjaW1hbABzZXRfTWluaW11bQBzZXRfTWF4aW11bQBvcF9JbXBsaWNpdABzZXRfVmFsdWUAQnV0dG9uAHNldF9EaWFsb2dSZXN1bHQAQ29udHJvbENvbGxlY3Rpb24AZ2V0X0NvbnRyb2xzAElCdXR0b25Db250cm9sAHNldF9BY2NlcHRCdXR0b24AU2hvd0RpYWxvZwBnZXRfVmFsdWUAb3BfRXhwbGljaXQAU3lzdGVtLklPAEZpbGUARXhpc3RzAFJlYWRBbGxUZXh0AFRyaW0AVHJ5UGFyc2UAVG9TdHJpbmcAV3JpdGVBbGxUZXh0AE1pY3Jvc29mdC5XaW4zMgBSZWdpc3RyeQBSZWdpc3RyeUtleQBDdXJyZW50VXNlcgBPcGVuU3ViS2V5AEdldFZhbHVlAGdldF9FeGVjdXRhYmxlUGF0aABvcF9FcXVhbGl0eQBJRGlzcG9zYWJsZQBEaXNwb3NlAERlbGV0ZVZhbHVlAFNldFZhbHVlAEV4aXQAQml0bWFwAEdyYXBoaWNzAEltYWdlAEZyb21JbWFnZQBDb2xvcgBGcm9tQXJnYgBCcnVzaGVzAEJydXNoAGdldF9XaGl0ZQBGaWxsRWxsaXBzZQBHZXRIaWNvbgBGcm9tSGFuZGxlAC5jY3RvcgAAAAAdQgByAGUAYQBrACAAUgBlAG0AaQBuAGQAZQByAAAxTgBlAHgAdAAgAGIAcgBlAGEAawAgAGkAbgA6ACAAewAwAH0AbQAgAHsAMQB9AHMAABFTAGUAdAB0AGkAbgBnAHMAAC9BAHUAdABvACAAUwB0AGEAcgB0ACAAdwBpAHQAaAAgAFcAaQBuAGQAbwB3AHMAAAlRAHUAaQB0AAADLQABFVMAeQBzAHQAZQBtAEgAYQBuAGQAAICvWQBvAHUAIABoAGEAdgBlACAAYgBlAGUAbgAgAHcAbwByAGsAaQBuAGcAIABmAG8AcgAgAHsAMAB9ACAAbQBpAG4AdQB0AGUAcwAuACAAUABsAGUAYQBzAGUAIAB0AGEAawBlACAAYQAgAGIAcgBlAGEAawAsACAAcgBlAHMAdAAgAHkAbwB1AHIAIABlAHkAZQBzACAAYQBuAGQAIABzAHQAcgBlAHQAYwBoAC4AACNUAGkAbQBlACAAZgBvAHIAIABhACAAQgByAGUAYQBrACEAAD9FAG4AdABlAHIAIABiAHIAZQBhAGsAIABpAG4AdABlAHIAdgBhAGwAIAAoAG0AaQBuAHUAdABlAHMAKQA6AAAFTwBLAABLUgBlAG0AaQBuAGQAZQByACAAaQBuAHQAZQByAHYAYQBsACAAcwBlAHQAIAB0AG8AIAB7ADAAfQAgAG0AaQBuAHUAdABlAHMALgAAHVMAZQB0AHQAaQBuAGcAcwAgAFMAYQB2AGUAZAAAW1MAbwBmAHQAdwBhAHIAZQBcAE0AaQBjAHIAbwBzAG8AZgB0AFwAVwBpAG4AZABvAHcAcwBcAEMAdQByAHIAZQBuAHQAVgBlAHIAcwBpAG8AbgBcAFIAdQBuAAAbQgByAGUAYQBrAFIAZQBtAGkAbgBkAGUAcgAAFWMAbwBuAGYAaQBnAC4AdAB4AHQAAAAA6a/lUH4O7EeyZPz6mZx11gAIt3pcVhk04IkCBgkEAAABAAQBAAAABAgAAAAGAAMCDhgJAwYSCQMGEg0DBhIRAgYIAwYRFQIGDgMAAAEGAAIBHBIZAwAAAgiwP19/EdUKOgQAABIdBCABAQgDIAABBCABAQ4EAAEBAgUgAgEcGAUgAQESNQUgAQESHQUgAQESDQQgAQECBAAAERUFIAERFQ0EBwERFQQgABI9CAACEUERFREVAyAADQMGEUEDIAAIBgADDg4cHAYgAgEOEjUFIAEIEk0FIAESTQ4OBwcRQQ4STRJNEk0STQICBhgFAAIODhwOAAYRWQ4OEV0RYRFlEWkFAAIICAgFIAIOCAgIBwQRQQ4CERUFIAEBEXkFIAEBEX0GIAEBEYCJBgABEYCJCAUgAQERWQUgABKAkQUgAQESdQYgAQESgJUEIAARWQUgABGAiQYAAQgRgIkKAAQRWQ4OEV0RYRsHChJxEoCBEoCFEoCNEnESgIESgIUSgI0CERUEAAECDgQAAQ4OAyAADgYAAgIOEAgFBwMOCAIFAAIBDg4EBhKAoQcgAhKAoQ4CBCABHA4DAAAOBQACAg4OCAcEEoChHAICBSACAQ4CBSACAQ4cBgcCEoChAgUgAgEICAgAARKArRKAsQgAAxGAtQgICAYgAQERgLUFAAASgL0KIAUBEoC9CAgICAMgABgFAAESHRgMBwUSgKkSgK0YEh0CCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQAAxDkAAAAAAAAAAAAA3jkAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAANA5AAAAAAAAAAAAAAAAX0NvckV4ZU1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAIAAAgBgAAAA4AACAAAAAAAAAAAAAAAAAAAABAAEAAABQAACAAAAAAAAAAAAAAAAAAAABAAEAAABoAACAAAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAAAAAAAAAAAAAAABAAAAAACQAAAAoEAAAFwCAAAAAAAAAAAAAABDAADqAQAAAAAAAAAAAABcAjQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEvAEAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAmAEAAAEAMAAwADAAMAAwADQAYgAwAAAALAACAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAACAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADAALgAwAC4AMAAuADAAAABEABIAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEIAcgBlAGEAawBSAGUAbQBpAG4AZABlAHIALgBlAHgAZQAAACgAAgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAACAAAABMABIAAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAQgByAGUAYQBrAFIAZQBtAGkAbgBkAGUAcgAuAGUAeABlAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAwAC4AMAAuADAALgAwAAAAAAAAAO+7vzw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5ZXMiPz4NCjxhc3NlbWJseSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEiIG1hbmlmZXN0VmVyc2lvbj0iMS4wIj4NCiAgPGFzc2VtYmx5SWRlbnRpdHkgdmVyc2lvbj0iMS4wLjAuMCIgbmFtZT0iTXlBcHBsaWNhdGlvbi5hcHAiLz4NCiAgPHRydXN0SW5mbyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjIiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgIDxyZXF1ZXN0ZWRQcml2aWxlZ2VzIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1aUFjY2Vzcz0iZmFsc2UiLz4NCiAgICAgIDwvcmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3NlY3VyaXR5Pg0KICA8L3RydXN0SW5mbz4NCjwvYXNzZW1ibHk+DQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAMAAAA8DkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
                
                byte[] exeBytes = Convert.FromBase64String(b64);
                
                // Kill if running
                foreach (var process in Process.GetProcessesByName("BreakReminder"))
                {
                    try { process.Kill(); process.WaitForExit(2000); } catch { }
                }
                
                System.IO.File.WriteAllBytes(exePath, exeBytes);
                
                // Create Shortcut using COM
                string startMenu = Environment.GetFolderPath(Environment.SpecialFolder.Programs);
                string shortcutPath = Path.Combine(startMenu, "Break Reminder.lnk");
                
                CreateShortcut(shortcutPath, exePath, "Reminds you to take a break");
                
                // Set Auto Start using Registry
                using (Microsoft.Win32.RegistryKey key = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run", true))
                {
                    key.SetValue("BreakReminder", exePath);
                }
                
                MessageBox.Show("Installation complete! Break Reminder is now running and will auto-start with Windows.", "Setup Complete", MessageBoxButtons.OK, MessageBoxIcon.Information);
                
                Process.Start(new ProcessStartInfo()
                {
                    FileName = exePath,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                MessageBox.Show("Installation failed:\n" + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
        
        static void CreateShortcut(string shortcutPath, string targetPath, string description)
        {
            try
            {
                Type t = Type.GetTypeFromProgID("WScript.Shell");
                dynamic shell = Activator.CreateInstance(t);
                var shortcut = shell.CreateShortcut(shortcutPath);
                shortcut.TargetPath = targetPath;
                shortcut.WorkingDirectory = Path.GetDirectoryName(targetPath);
                shortcut.Description = description;
                shortcut.IconLocation = targetPath + ",0";
                shortcut.Save();
            }
            catch {}
        }
    }
}
